(cl:defpackage sinwave-srv
  (:use )
  (:export
   "ADDTWODATAPOINTS"
   "<ADDTWODATAPOINTS-REQUEST>"
   "ADDTWODATAPOINTS-REQUEST"
   "<ADDTWODATAPOINTS-RESPONSE>"
   "ADDTWODATAPOINTS-RESPONSE"
  ))

