// Generated by gencpp from file sinwave/AddTwoDataPoints.msg
// DO NOT EDIT!


#ifndef SINWAVE_MESSAGE_ADDTWODATAPOINTS_H
#define SINWAVE_MESSAGE_ADDTWODATAPOINTS_H

#include <ros/service_traits.h>


#include <sinwave/AddTwoDataPointsRequest.h>
#include <sinwave/AddTwoDataPointsResponse.h>


namespace sinwave
{

struct AddTwoDataPoints
{

typedef AddTwoDataPointsRequest Request;
typedef AddTwoDataPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoDataPoints
} // namespace sinwave


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sinwave::AddTwoDataPoints > {
  static const char* value()
  {
    return "90646d2d2f45747163c2b98b43301e86";
  }

  static const char* value(const ::sinwave::AddTwoDataPoints&) { return value(); }
};

template<>
struct DataType< ::sinwave::AddTwoDataPoints > {
  static const char* value()
  {
    return "sinwave/AddTwoDataPoints";
  }

  static const char* value(const ::sinwave::AddTwoDataPoints&) { return value(); }
};


// service_traits::MD5Sum< ::sinwave::AddTwoDataPointsRequest> should match 
// service_traits::MD5Sum< ::sinwave::AddTwoDataPoints > 
template<>
struct MD5Sum< ::sinwave::AddTwoDataPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sinwave::AddTwoDataPoints >::value();
  }
  static const char* value(const ::sinwave::AddTwoDataPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sinwave::AddTwoDataPointsRequest> should match 
// service_traits::DataType< ::sinwave::AddTwoDataPoints > 
template<>
struct DataType< ::sinwave::AddTwoDataPointsRequest>
{
  static const char* value()
  {
    return DataType< ::sinwave::AddTwoDataPoints >::value();
  }
  static const char* value(const ::sinwave::AddTwoDataPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sinwave::AddTwoDataPointsResponse> should match 
// service_traits::MD5Sum< ::sinwave::AddTwoDataPoints > 
template<>
struct MD5Sum< ::sinwave::AddTwoDataPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sinwave::AddTwoDataPoints >::value();
  }
  static const char* value(const ::sinwave::AddTwoDataPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sinwave::AddTwoDataPointsResponse> should match 
// service_traits::DataType< ::sinwave::AddTwoDataPoints > 
template<>
struct DataType< ::sinwave::AddTwoDataPointsResponse>
{
  static const char* value()
  {
    return DataType< ::sinwave::AddTwoDataPoints >::value();
  }
  static const char* value(const ::sinwave::AddTwoDataPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINWAVE_MESSAGE_ADDTWODATAPOINTS_H
