// Generated by gencpp from file sinwave/AddTwoDataPointsRequest.msg
// DO NOT EDIT!


#ifndef SINWAVE_MESSAGE_ADDTWODATAPOINTSREQUEST_H
#define SINWAVE_MESSAGE_ADDTWODATAPOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sinwave/TimeSeriesPoint.h>
#include <sinwave/TimeSeriesPoint.h>

namespace sinwave
{
template <class ContainerAllocator>
struct AddTwoDataPointsRequest_
{
  typedef AddTwoDataPointsRequest_<ContainerAllocator> Type;

  AddTwoDataPointsRequest_()
    : a()
    , b()  {
    }
  AddTwoDataPointsRequest_(const ContainerAllocator& _alloc)
    : a(_alloc)
    , b(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sinwave::TimeSeriesPoint_<ContainerAllocator>  _a_type;
  _a_type a;

   typedef  ::sinwave::TimeSeriesPoint_<ContainerAllocator>  _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoDataPointsRequest_

typedef ::sinwave::AddTwoDataPointsRequest_<std::allocator<void> > AddTwoDataPointsRequest;

typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsRequest > AddTwoDataPointsRequestPtr;
typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsRequest const> AddTwoDataPointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sinwave

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sinwave': ['/workspace/ros_ws/src/sinwave/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c4eee4645daadd95e3d676865ad4520";
  }

  static const char* value(const ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c4eee4645daadd9ULL;
  static const uint64_t static_value2 = 0x5e3d676865ad4520ULL;
};

template<class ContainerAllocator>
struct DataType< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sinwave/AddTwoDataPointsRequest";
  }

  static const char* value(const ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TimeSeriesPoint a\n\
TimeSeriesPoint b\n\
\n\
================================================================================\n\
MSG: sinwave/TimeSeriesPoint\n\
float64 value\n\
float64 timestamp\n\
";
  }

  static const char* value(const ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoDataPointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sinwave::AddTwoDataPointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    s << std::endl;
    Printer< ::sinwave::TimeSeriesPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    s << std::endl;
    Printer< ::sinwave::TimeSeriesPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINWAVE_MESSAGE_ADDTWODATAPOINTSREQUEST_H
