// Generated by gencpp from file sinwave/AddTwoDataPointsResponse.msg
// DO NOT EDIT!


#ifndef SINWAVE_MESSAGE_ADDTWODATAPOINTSRESPONSE_H
#define SINWAVE_MESSAGE_ADDTWODATAPOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sinwave/TimeSeriesPoint.h>

namespace sinwave
{
template <class ContainerAllocator>
struct AddTwoDataPointsResponse_
{
  typedef AddTwoDataPointsResponse_<ContainerAllocator> Type;

  AddTwoDataPointsResponse_()
    : sum()  {
    }
  AddTwoDataPointsResponse_(const ContainerAllocator& _alloc)
    : sum(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sinwave::TimeSeriesPoint_<ContainerAllocator>  _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoDataPointsResponse_

typedef ::sinwave::AddTwoDataPointsResponse_<std::allocator<void> > AddTwoDataPointsResponse;

typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsResponse > AddTwoDataPointsResponsePtr;
typedef boost::shared_ptr< ::sinwave::AddTwoDataPointsResponse const> AddTwoDataPointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sinwave

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sinwave': ['/workspace/ros_ws/src/sinwave/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d71e72c52ec1917c6d171c3a0e0a3f1e";
  }

  static const char* value(const ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd71e72c52ec1917cULL;
  static const uint64_t static_value2 = 0x6d171c3a0e0a3f1eULL;
};

template<class ContainerAllocator>
struct DataType< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sinwave/AddTwoDataPointsResponse";
  }

  static const char* value(const ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TimeSeriesPoint sum\n\
\n\
\n\
================================================================================\n\
MSG: sinwave/TimeSeriesPoint\n\
float64 value\n\
float64 timestamp\n\
";
  }

  static const char* value(const ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddTwoDataPointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sinwave::AddTwoDataPointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    s << std::endl;
    Printer< ::sinwave::TimeSeriesPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINWAVE_MESSAGE_ADDTWODATAPOINTSRESPONSE_H
