/* Auto-generated by create_boost_header.py for file /workspace/ros_ws/src/sinwave/msg/TimeSeriesPoint.msg */
#ifndef SINWAVE_BOOST_SERIALIZATION_TIMESERIESPOINT_H
#define SINWAVE_BOOST_SERIALIZATION_TIMESERIESPOINT_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/string.hpp>
#include <sinwave/TimeSeriesPoint.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::sinwave::TimeSeriesPoint_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("value",m.value);
    a & make_nvp("timestamp",m.timestamp);
}

} // namespace serialization
} // namespace boost

#endif // SINWAVE_BOOST_SERIALIZATION_TIMESERIESPOINT_H

