# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sinwave/AddTwoDataPointsRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sinwave.msg

class AddTwoDataPointsRequest(genpy.Message):
  _md5sum = "3c4eee4645daadd95e3d676865ad4520"
  _type = "sinwave/AddTwoDataPointsRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """TimeSeriesPoint a
TimeSeriesPoint b

================================================================================
MSG: sinwave/TimeSeriesPoint
float64 value
float64 timestamp
"""
  __slots__ = ['a','b']
  _slot_types = ['sinwave/TimeSeriesPoint','sinwave/TimeSeriesPoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       a,b

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddTwoDataPointsRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.a is None:
        self.a = sinwave.msg.TimeSeriesPoint()
      if self.b is None:
        self.b = sinwave.msg.TimeSeriesPoint()
    else:
      self.a = sinwave.msg.TimeSeriesPoint()
      self.b = sinwave.msg.TimeSeriesPoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.a.value, _x.a.timestamp, _x.b.value, _x.b.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.a is None:
        self.a = sinwave.msg.TimeSeriesPoint()
      if self.b is None:
        self.b = sinwave.msg.TimeSeriesPoint()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.a.value, _x.a.timestamp, _x.b.value, _x.b.timestamp,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.a.value, _x.a.timestamp, _x.b.value, _x.b.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.a is None:
        self.a = sinwave.msg.TimeSeriesPoint()
      if self.b is None:
        self.b = sinwave.msg.TimeSeriesPoint()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.a.value, _x.a.timestamp, _x.b.value, _x.b.timestamp,) = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sinwave/AddTwoDataPointsResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sinwave.msg

class AddTwoDataPointsResponse(genpy.Message):
  _md5sum = "d71e72c52ec1917c6d171c3a0e0a3f1e"
  _type = "sinwave/AddTwoDataPointsResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """TimeSeriesPoint sum


================================================================================
MSG: sinwave/TimeSeriesPoint
float64 value
float64 timestamp
"""
  __slots__ = ['sum']
  _slot_types = ['sinwave/TimeSeriesPoint']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AddTwoDataPointsResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sum is None:
        self.sum = sinwave.msg.TimeSeriesPoint()
    else:
      self.sum = sinwave.msg.TimeSeriesPoint()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d().pack(_x.sum.value, _x.sum.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.sum is None:
        self.sum = sinwave.msg.TimeSeriesPoint()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.sum.value, _x.sum.timestamp,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d().pack(_x.sum.value, _x.sum.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.sum is None:
        self.sum = sinwave.msg.TimeSeriesPoint()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.sum.value, _x.sum.timestamp,) = _get_struct_2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
class AddTwoDataPoints(object):
  _type          = 'sinwave/AddTwoDataPoints'
  _md5sum = '90646d2d2f45747163c2b98b43301e86'
  _request_class  = AddTwoDataPointsRequest
  _response_class = AddTwoDataPointsResponse
